### ISSUE TITLE
Are you able to run with 6.7.1

### ISSUE THREAD

**Issue by olsonnn** [angela-d/brain-dump#4]
Great page you've created here! thanks for that.
But 6.7.1 seems to break my setup:  dateMath.parse is not a function

**Comment by angela-d** [comment]
I haven't tested on 6.7.1 yet, I've seen problems others are having so I'm hoping to have some time to give it a run myself, soon!

I know in 6.7 they were switching to React from Angular and a little code block is needed to 'fix' the transition, I've not attempted to run it, myself.

I just went to the Grafana site to pull up the referenced changelog and it looks like they had a marketing team design their site, I can't find anything useful as easily as before.. when I get a chance to give it a spin I'll post back!

**Comment by olsonnn** [comment]
any update on this one?

**Comment by angela-d** [comment]
I haven't had a chance to do any testing with Grafana lately, but I have seen others say upgrading to 6.7.2 fixed this bug:
https://github.com/neuralfraud/grafana-prtg/issues/163

**Comment by olsonnn** [comment]
Doh.. i could have find this my self! but i didn't expect it was a Grafana issue.
Confirmed! 6.7.2 works fine again!

**Comment by angela-d** [comment]
I was expecting this to be a bug in the plugin, as well.  There was a warning in the Grafana changelog a while back, about a change from Ansible to React expected to break plugins going forward and I thought it was just about that time.. turns out not so!
