### ISSUE TITLE
PRTG Grafana Error

### ISSUE THREAD

**Issue by mafer0410** [angela-d/brain-dump#6]
I have tried to make a graph with the PRTG data, and I get the following error.
error
![error](https://user-images.githubusercontent.com/51204835/80550329-13f87e80-89c0-11ea-87fb-a5636cb3ab82.png)

**Comment by angela-d** [comment]
What version of Grafana are you using?
[6.7.1 was broken with neuralfraud's extension](https://github.com/neuralfraud/grafana-prtg/issues/163) - Grafana v6.7.0-pre (63d999a739) and 6.7.2 (according to other users) are the latest Grafana versions that work with this plugin.

Another thing to check:
Don't type any entries in Group, Host, Sensor or Channel - they should automatically populate with pull-downs as you *begin to type their names* (slowly type *Sit* and Sitios Web should appear in a pull-down menu).  

If they do not, the data won't be captured for the display.

**Comment by mafer0410** [comment]
I have solved the problem, thank you very much.
