### ISSUE TITLE
Grafana PRTG Variables

### ISSUE THREAD

**Issue by mafer0410** [angela-d/brain-dump#7]
Hi good day,
I have been using Grafana with PRTG, and I have only one question regarding the creation of variables. I know there are several types of variables: interval, query etc.
I would like to know how the type of query is used, the syntax to recognize, and in which situations each type of variable is used.

**Comment by angela-d** [comment]
I'm not really sure of the context of your question.  Are you referring to Grafana custom variables in relation to neuralfraud's plugin?

If you're referring to the plugin itself, can you provide screenshots and examples or scenarios of what you're trying to do?
