### ISSUE TITLE
Filtering

### ISSUE THREAD

**Issue by reuvygroovy** [angela-d/brain-dump#8]
Can you explain to me how I can use the filter for example to filter by tags?

I for example added a tag to the PRTG sensor (ex. "test") and tried to use the field to filter by "tag" and inputted to regex "/^test/" but it doesn't do anything

**Comment by angela-d** [comment]
For regex sorting, try:
```text
/test/
```

instead of `/^test/`

If that doesn't work, see if this thread has the type of filtering you're after: https://github.com/neuralfraud/grafana-prtg/issues/154
